---
dependency:
  name: galaxy
  options:
    role-file: molecule/shared/requirements.yml

driver:
  name: vagrant
  provider:
    name: virtualbox

lint:
  name: yamllint
  options:
    config-file: molecule/shared/.yaml_lint.yml

platforms:
  # https://app.vagrantup.com/boxes/search?provider=virtualbox
  - name: v-centos7
    box: centos/7
    provider_options:
      memory: 1024
      cpus: 1
    groups:
      - centos


provisioner:
  name: ansible
  playbooks:
    converge: ../shared/playbook.yml
  inventory:
    group_vars:
      ubuntu:
        ansible_python_interpreter: /usr/bin/python3
  lint:
    name: ansible-lint

scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - destroy

verifier:
  name: testinfra
  directory: ../shared/tests/
  lint:
    name: flake8
