---
dependency:
  name: galaxy
  options:
    role-file: molecule/shared/requirements.yml


driver:
  name: vagrant
  provider:
    name: libvirt


lint:
  name: yamllint
  options:
    config-file: molecule/shared/.yaml_lint.yml


platforms:
  # https://app.vagrantup.com/boxes/search?provider=libvirt
  - name: "${ROLE_CI_PREFIX:-l}-centos7"
    box: centos/7
    interfaces:
      - network_name: private_network
        type: static
        auto_config: true
        ip: 192.168.90.205
    provider_options:
      memory: 1024
      cpus: 1
      uri: "'qemu:///system'"
    groups:
      - centos


provisioner:
  name: ansible
  playbooks:
    converge: ../shared/playbook.yml
  config_options:
    defaults:
      log_path: "${CLONE_DIR:-.}/ansible.log"
      stdout_callback: debug
      verbosity: 2
    diff:
      always: true
  inventory:
    group_vars:
      ubuntu:
        ansible_python_interpreter: /usr/bin/python3
  lint:
    name: ansible-lint


scenario:
  name: libvirt
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - destroy


verifier:
  name: testinfra
  directory: ../shared/tests/
  lint:
    name: flake8
